### ISSUE TITLE
Method index mismatch

### ISSUE THREAD

**Issue by maekoos** [mdeg/dexparser#2]
Hi! I believe I've found a bug in the way the `transform_encoded_methods` keeps track of the offset.

When updating `prev_offset` it is currently set to `method.method_idx_diff`, but should (probably) be set to the sum of `prev_offset` and `method.method_idx_diff`

https://github.com/mdeg/dexparser/blob/0233b7e25d9510189c7022c7be5796d780d01baf/src/parser/parse_data.rs#L367

**Comment by mdeg** [comment]
Thanks for the contribution! Glad to see this is being used.

That certainly seems reasonable - I'll take a look at it later today.

**Comment by mdeg** [comment]
@maekoos I've merged this and pushed a new version, `0.6.2`, to crates.io with the fix. Thanks again for the submission.
